In [2]:
import pandas as pd
from glob import glob
pd.set_option('display.max_columns', None)

df1 = pd.read_csv("../../data/raw/Test-1542969243754.csv")
df2 = pd.read_csv("../../data/raw/Test_Beneficiarydata-1542969243754.csv")
df3 = pd.read_csv("../../data/raw/Test_Inpatientdata-1542969243754.csv")
df4 = pd.read_csv("../../data/raw/Test_Outpatientdata-1542969243754.csv")
df5 = pd.read_csv("../../data/raw/Train-1542865627584.csv")
df6 = pd.read_csv("../../data/raw/Train_Beneficiarydata-1542865627584.csv")
df7 = pd.read_csv("../../data/raw/Train_Inpatientdata-1542865627584.csv")
df8 = pd.read_csv("../../data/raw/Train_Outpatientdata-1542865627584.csv")

In [11]:
df1

      Provider
0     PRV51002
1     PRV51006
2     PRV51009
3     PRV51010
4     PRV51018
...        ...
1348  PRV57713
1349  PRV57726
1350  PRV57745
1351  PRV57749
1352  PRV57750

[1353 rows x 1 columns]

In [3]:
df5.groupby(['PotentialFraud']).count()

                Provider
PotentialFraud
No                  4904
Yes                  506

In [5]:
df5

      Provider PotentialFraud
0     PRV51001             No
1     PRV51003            Yes
2     PRV51004             No
3     PRV51005            Yes
4     PRV51007             No
...        ...            ...
5405  PRV57759             No
5406  PRV57760             No
5407  PRV57761             No
5408  PRV57762             No
5409  PRV57763             No

[5410 rows x 2 columns]

In [24]:
df6

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaN,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,NaN,2,1,0,39,280,12,12,2,2,2,2,2,2,2,2,2,2,2,0,0,30,50
2,BENE11003,1936-08-01,NaN,1,1,0,52,590,12,12,1,2,2,2,2,2,2,1,2,2,2,0,0,90,40
3,BENE11004,1922-07-01,NaN,1,1,0,39,270,12,12,1,1,2,2,2,2,1,1,1,1,2,0,0,1810,760
4,BENE11005,1935-09-01,NaN,1,1,0,24,680,12,12,2,2,2,2,1,2,1,2,2,2,2,0,0,1790,1200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138551,BENE159194,1939-07-01,NaN,1,1,0,39,140,12,12,1,2,2,2,2,2,2,2,2,2,2,0,0,430,460
138552,BENE159195,1938-12-01,NaN,2,1,0,49,530,12,12,1,2,2,2,2,2,1,2,2,2,2,0,0,880,100
138553,BENE159196,1916-06-01,NaN,2,1,0,6,150,12,12,2,1,1,1,2,1,1,1,2,2,2,2000,1068,3240,1390
138554,BENE159197,1930-01-01,NaN,1,1,0,16,560,12,12,1,1,2,2,2,2,2,1,2,2,2,0,0,2650,10
138555,BENE159198,1952-04-01,NaN,2,1,0,21,20,12,12,1,1,2,2,2,1,1,2,2,1,2,0,0,5470,1870

In [25]:
df7

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,6186,1068.0,2009-09-02,750,6186,2948,56400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,29590,1068.0,2009-09-20,883,29623,30390,71690,34590,V1581,32723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,431,1068.0,2009-02-22,067,43491,2762,7843,32723,V1041,4254,25062,40390,4019,NaN,331.0,NaN,NaN,NaN,NaN,NaN
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,78321,1068.0,2009-08-30,975,042,3051,34400,5856,42732,486,5119,29620,20300,NaN,3893.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40469,BENE159167,CLM69886,2009-09-28,2009-10-02,PRV53671,7000,PHY345332,PHY319565,NaN,2009-09-28,2859,1068.0,2009-10-02,812,2851,2762,53550,V0254,V1005,5173,79092,70704,2869,4148,9904.0,NaN,NaN,NaN,NaN,NaN
40470,BENE159175,CLM74504,2009-11-03,2009-11-06,PRV54981,4000,PHY342806,PHY365497,NaN,2009-11-03,79902,1068.0,2009-11-06,228,42823,4148,4019,3970,4241,V1042,49122,4254,5990,NaN,8605.0,NaN,NaN,NaN,NaN,NaN
40471,BENE159177,CLM76485,2009-11-18,2009-11-22,PRV56588,3000,PHY423220,PHY332752,NaN,2009-11-18,78605,1068.0,2009-11-22,302,4280,3963,5859,4019,40390,4111,71534,71590,V4502,NaN,9390.0,NaN,NaN,NaN,NaN,NaN
40472,BENE159177,CLM79949,2009-12-17,2009-12-18,PRV56575,5000,PHY353156,NaN,NaN,2009-12-17,7802,1068.0,2009-12-18,309,7802,5859,496,2809,V1254,42822,4263,0414,41400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40473,BENE159188,CLM69948,2009-09-28,2009-10-06,PRV54765,15000,PHY431177,PHY352941,NaN,2009-09-28,1536,1068.0,2009-10-06,340,1540,27800,6146,2449,42830,412,4019,2800,27801,NaN,1733.0,NaN,NaN,NaN,NaN,NaN

In [26]:
df8

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,NaN,NaN,78943,V5866,V1272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,56409
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,NaN,NaN,6115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,79380
2,BENE11003,CLM438021,2009-06-27,2009-06-27,PRV57595,10,PHY328821,NaN,NaN,2723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,BENE11004,CLM121801,2009-01-06,2009-01-06,PRV56011,40,PHY334319,NaN,NaN,71988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
4,BENE11004,CLM150998,2009-01-22,2009-01-22,PRV56011,200,PHY403831,NaN,NaN,82382,30000,72887,4280,7197,V4577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,71947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517732,BENE159198,CLM510792,2009-08-06,2009-08-06,PRV53699,800,PHY364188,PHY364188,PHY385752,2163,V4575,53190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517733,BENE159198,CLM551294,2009-08-29,2009-08-29,PRV53702,400,PHY423019,PHY332284,NaN,07041,5781,25000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517734,BENE159198,CLM596444,2009-09-24,2009-09-24,PRV53676,60,PHY361063,NaN,NaN,V570,78079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517735,BENE159198,CLM636992,2009-10-18,2009-10-18,PRV53689,70,PHY403198,NaN,PHY419379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
517736,BENE159198,CLM686139,2009-11-17,2009-11-18,PRV53689,80,PHY419379,NaN,PHY419379,78900,78609,4280,71946,3310,75311,2724,V103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

One issue is that the labels are at the provider level but the data is at the claim level.

One approach is to aggregate data to the provider level.

### How many claims are there on average per provider?

Answer: 19.3

### How much do claims differ for a given provider?

It varies a lot.

### How much will the claims data be affecting the provider_has_potential_fraud result?

It has a big impact.

19.347036328871894

In [10]:
df7.provider.value_counts()

AttributeError: 'DataFrame' object has no attribute 'provider'

In [9]:
df7.loc[df7['Provider'] == 'PRV55912']

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1882,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN
2964,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN
3311,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN
3729,BENE24402,CLM32911,2009-01-08,2009-01-12,PRV55912,3000,PHY380413,PHY432598,NaN,2009-01-08,1748,1068.0,2009-01-12,593,2330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8543.0,NaN,NaN,NaN,NaN,NaN
4995,BENE28966,CLM56700,2009-06-22,2009-06-25,PRV55912,10000,PHY418191,PHY370861,NaN,2009-06-22,5180,1068.0,2009-06-25,184,1623,5180,496,4660,4019,42731,E8788,53081,42611,32723,3327.0,NaN,NaN,NaN,NaN,NaN
5081,BENE29251,CLM42062,2009-03-11,2009-03-19,PRV55912,18000,PHY318892,NaN,NaN,2009-03-11,7231,1068.0,2009-03-19,095,3501,2724,70715,42822,25060,3599,7802,41401,82525,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5780,BENE31905,CLM37729,2009-02-10,2009-03-03,PRV55912,13000,PHY319720,PHY392080,PHY380413,2009-02-10,43491,1068.0,2009-03-03,940,V5789,5849,78830,V4589,2859,4019,78820,7993,40390,NaN,3995.0,NaN,NaN,NaN,NaN,NaN
5781,BENE31905,CLM49964,2009-05-06,2009-05-09,PRV55912,7000,PHY340849,NaN,NaN,2009-05-06,78609,1068.0,2009-05-09,248,4280,5119,1629,41401,4589,V854,7564,4148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5784,BENE31905,CLM77968,2009-12-01,2009-12-05,PRV55912,7000,PHY410728,NaN,NaN,2009-12-01,5781,1068.0,2009-12-05,341,5579,2761,6822,6953,7140,25000,2768,60000,4019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5785,BENE31905,CLM80697,2009-12-25,2009-12-28,PRV55912,6000,PHY414999,PHY316408,NaN,2009-12-25,78605,1068.0,2009-12-28,199,49322,82525,5990,42731,53081,4019,4280,30000,V5869,NaN,8741.0,NaN,NaN,NaN,NaN,NaN
7343,BENE37685,CLM35228,2009-01-24,2009-01-25,PRV55912,7000,PHY414999,PHY344927,PHY315843,2009-01-24,1749,1068.0,2009-01-25,579,6820,4019,40390,42781,25000,53081,7845,NaN,NaN,NaN,4011.0,NaN,NaN,NaN,NaN,NaN
7345,BENE37685,CLM78693,2009-12-07,2009-12-14,PRV55912,4000,PHY410835,PHY420290,PHY370067,2009-12-07,7802,1068.0,2009-12-14,218,4580,V4364,29040,4019,V4365,29410,4299,25000,42731,NaN,2181.0,NaN,NaN,NaN,NaN,NaN
9481,BENE45976,CLM32244,2009-01-03,2009-01-14,PRV55912,10000,PHY361763,PHY323689,NaN,2009-01-03,41071,1068.0,2009-01-14,296,41041,53021,5119,5849,00841,2724,41400,5990,4239,NaN,3723.0,NaN,NaN,NaN,NaN,NaN
9616,BENE46443,CLM57392,2009-06-27,2009-06-30,PRV55912,4000,PHY333901,NaN,NaN,2009-06-27,79092,1068.0,2009-06-30,950,78097,2761,4280,4019,2760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10612,BENE50078,CLM46288,2009-04-09,2009-04-17,PRV55912,10000,PHY393882,NaN,NaN,2009-04-09,5990,1068.0,2009-04-17,872,03843,78552,2760,28521,42843,2761,40391,5990,20040,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10720,BENE50535,CLM66287,2009-09-01,2009-09-24,PRV55912,9000,PHY339551,PHY316408,NaN,2009-09-01,5789,1068.0,2009-09-24,368,4558,00845,5363,5856,59651,496,29620,70722,2449,NaN,9702.0,7881.0,496.0,NaN,NaN,NaN
11422,BENE53240,CLM31596,2008-12-30,2009-01-12,PRV55912,29000,PHY354336,PHY420290,NaN,2008-12-30,49121,1068.0,2009-01-12,988,486,1129,5856,5809,4019,56089,3051,V5331,591,NaN,3777.0,NaN,NaN,NaN,NaN,NaN
11423,BENE53240,CLM44999,2009-04-01,2009-04-06,PRV55912,9000,PHY384397,PHY370861,NaN,2009-04-01,5781,1068.0,2009-04-06,358,53440,56210,5854,29620,42731,V1003,40390,78559,4111,NaN,4513.0,NaN,NaN,NaN,NaN,NaN
11454,BENE53373,CLM35318,2009-01-24,2009-01-26,PRV55912,10000,PHY416660,PHY401594,NaN,2009-01-24,78650,1068.0,2009-01-26,284,41011,7804,41404,4271,V4581,25000,496,412,2740,NaN,66.0,4019.0,NaN,NaN,NaN,NaN
11721,BENE54325,CLM75451,2009-11-11,2009-11-14,PRV55912,7000,PHY403495,PHY416976,NaN,2009-11-11,6238,1068.0,2009-11-14,742,6151,2851,4280,5859,25000,4019,5601,NaN,NaN,NaN,6859.0,NaN,NaN,NaN,NaN,NaN
11905,BENE54995,CLM78587,2009-12-06,2009-12-18,PRV55912,17000,PHY330172,NaN,NaN,2009-12-06,V5789,1068.0,2009-12-18,949,V5789,5990,431,4589,43491,7197,2851,60000,2724,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12209,BENE56010,CLM68920,2009-09-21,2009-09-23,PRV55912,8000,PHY429166,PHY339238,PHY343832,2009-09-21,40391,1068.0,2009-09-23,618,27651,42731,78791,E8881,25000,1122,5990,29590,185,NaN,3893.0,NaN,NaN,NaN,NaN,NaN
12827,BENE58359,CLM51613,2009-05-18,2009-05-20,PRV55912,12000,PHY339551,PHY342902,NaN,2009-05-18,2761,1068.0,2009-05-20,689,5960,60001,5363,70724,99592,5070,4010,8670,E8844,NaN,9604.0,NaN,NaN,NaN,NaN,NaN
13567,BENE61024,CLM52267,2009-05-22,2009-05-27,PRV55912,34000,PHY320873,PHY428304,NaN,2009-05-22,V552,1068.0,2009-05-27,356,1530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1734.0,NaN,NaN,NaN,NaN,NaN
14516,BENE64486,CLM55743,2009-06-15,2009-06-30,PRV55912,31000,PHY354336,PHY320126,NaN,2009-06-15,56985,1068.0,2009-06-30,387,55221,56722,2449,5849,5570,6172,2761,V5866,486,NaN,4573.0,NaN,NaN,NaN,NaN,NaN
14632,BENE64906,CLM73416,2009-10-25,2009-10-27,PRV55912,13000,PHY390614,PHY323689,NaN,2009-10-25,25208,1068.0,2009-10-27,623,2271,3051,42821,2752,4264,E8786,5185,V4511,40391,NaN,639.0,NaN,NaN,NaN,NaN,NaN
15681,BENE68644,CLM56253,2009-06-19,2009-06-23,PRV55912,11000,PHY361763,NaN,NaN,2009-06-19,2512,1068.0,2009-06-23,687,99664,42830,25000,5990,34401,70724,591,79029,6259,71590,NaN,NaN,NaN,NaN,NaN,NaN
16268,BENE70733,CLM38438,2009-02-14,2009-02-17,PRV55912,6000,PHY370861,NaN,PHY431474,2009-02-14,7802,1068.0,2009-02-17,229,7802,25000,3384,4280,40390,53081,42781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17340,BENE74730,CLM71754,2009-10-12,2009-11-08,PRV55912,11000,PHY414999,PHY412955,NaN,2009-10-12,25080,1068.0,2009-11-08,620,25080,V5867,27801,04102,68110,2760,6827,2761,40391,NaN,8412.0,NaN,NaN,NaN,NaN,NaN
17563,BENE75561,CLM73646,2009-10-27,2009-10-31,PRV55912,6000,PHY339551,NaN,NaN,2009-10-27,7862,1068.0,2009-10-31,193,486,49390,V1251,40390,2761,25042,41400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17564,BENE75561,CLM76927,2009-11-22,2009-11-23,PRV55912,4000,PHY368401,PHY320126,NaN,2009-11-22,42732,1068.0,2009-11-23,261,42731,1985,496,5859,4589,4019,2800,V1089,2768,NaN,9961.0,NaN,NaN,NaN,NaN,NaN
18054,BENE77314,CLM68252,2009-09-16,2009-09-22,PRV55912,34000,PHY387346,PHY414999,NaN,2009-09-16,56089,1068.0,2009-09-22,858,0389,5185,5849,25000,51881,486,5119,2768,28489,NaN,4579.0,NaN,NaN,NaN,NaN,NaN
18768,BENE79742,CLM31493,2008-12-29,2009-01-04,PRV55912,37000,PHY335210,NaN,NaN,2008-12-29,78097,1068.0,2009-01-04,035,34831,27651,319,2948,V140,25000,49121,E9289,4019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18939,BENE80270,CLM64833,2009-08-21,2009-08-26,PRV55912,52000,PHY390043,PHY414999,NaN,2009-08-21,41401,1068.0,2009-08-26,312,4271,78079,412,41401,V4581,V1254,2768,53081,25000,NaN,3794.0,4019.0,NaN,NaN,NaN,NaN
20969,BENE87712,CLM65300,2009-08-25,2009-09-10,PRV55912,7000,PHY414999,NaN,NaN,2009-08-25,7231,1068.0,2009-09-10,457,7213,4720,1970,25000,2662,73300,E9352,7820,56400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21249,BENE88798,CLM38727,2009-02-16,2009-02-21,PRV55912,3000,PHY410835,NaN,NaN,2009-02-16,00845,1068.0,2009-02-21,353,53550,28800,7993,4019,0414,2875,1970,4251,2720,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21311,BENE88996,CLM49993,2009-05-06,2009-05-09,PRV55912,4000,PHY414999,NaN,NaN,2009-05-06,78079,1068.0,2009-05-09,628,27651,1977,40390,3501,4019,7802,2720,70719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21831,BENE90846,CLM80859,2009-12-27,2009-12-29,PRV55912,18000,PHY399908,PHY402718,NaN,2009-12-27,4414,1068.0,2009-12-29,230,4414,E9379,41401,4019,71595,2875,4148,5571,53081,NaN,3971.0,5789.0,NaN,NaN,NaN,NaN
22746,BENE94212,CLM53712,2009-06-01,2009-06-04,PRV55912,7000,PHY380413,NaN,NaN,2009-06-01,2859,1068.0,2009-06-04,281,4280,V4976,496,2724,4659,41401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25752,BENE105393,CLM62763,2009-08-06,2009-08-09,PRV55912,4000,PHY420794,NaN,NaN,2009-08-06,78650,1068.0,2009-08-09,217,4280,5859,2859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26589,BENE108491,CLM66454,2009-09-02,2009-09-08,PRV55912,5000,PHY370861,NaN,PHY375237,2009-09-02,78605,1068.0,2009-09-08,208,486,2449,4019,4240,4280,1629,30590,2738,3004,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28668,BENE116116,CLM48213,2009-04-23,2009-04-27,PRV55912,10000,PHY368401,NaN,NaN,2009-04-23,486,1068.0,2009-04-27,203,486,41072,37230,41401,2760,2948,5119,34590,5856,51881,NaN,NaN,NaN,NaN,NaN,NaN
29535,BENE119291,CLM40155,2009-02-26,2009-03-01,PRV55912,8000,PHY393882,NaN,NaN,2009-02-26,78009,1068.0,2009-03-01,623,27651,E8780,3572,5856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30104,BENE121277,CLM61567,2009-07-28,2009-08-04,PRV55912,17000,PHY400663,PHY388520,NaN,2009-07-28,78701,1068.0,2009-08-04,687,V561,70723,412,99592,2948,5119,4148,5856,04112,NaN,3950.0,NaN,NaN,NaN,NaN,NaN
30277,BENE121804,CLM41095,2009-03-04,2009-03-06,PRV55912,2000,PHY414999,NaN,NaN,2009-03-04,42789,1068.0,2009-03-06,305,42731,33829,V453,42761,496,V5865,42781,71690,78057,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30278,BENE121804,CLM63178,2009-08-09,2009-08-12,PRV55912,6000,PHY410835,PHY370861,NaN,2009-08-09,7851,1068.0,2009-08-12,246,42731,4019,79029,25000,78659,28529,27802,57420,2900,NaN,8914.0,NaN,NaN,NaN,NaN,NaN
30930,BENE124092,CLM34009,2009-01-15,2009-01-16,PRV55912,4000,PHY370861,PHY370861,NaN,2009-01-15,5789,1068.0,2009-01-16,375,53783,2948,4019,V5861,412,78900,73300,42731,53190,NaN,4523.0,NaN,NaN,NaN,NaN,NaN
31350,BENE125702,CLM33226,2009-01-10,2009-01-17,PRV55912,12000,PHY403495,PHY417698,NaN,2009-01-10,41071,1068.0,2009-01-17,246,41071,6960,5849,2639,25012,2762,42832,0389,78722,NaN,9672.0,NaN,NaN,NaN,NaN,NaN
31531,BENE126334,CLM46735,2009-04-12,2009-04-20,PRV55912,8000,PHY382830,PHY330632,NaN,2009-04-12,71945,1068.0,2009-04-20,545,73313,E8490,4928,4019,25000,2449,NaN,NaN,NaN,NaN,7749.0,NaN,NaN,NaN,NaN,NaN
32259,BENE129061,CLM69274,2009-09-23,2009-09-28,PRV55912,8000,PHY323689,PHY323689,NaN,2009-09-23,5609,1068.0,2009-09-28,369,56089,58881,4280,2767,3051,05319,5990,78830,2768,NaN,9915.0,NaN,NaN,NaN,NaN,NaN
32392,BENE129539,CLM64072,2009-08-16,2009-08-19,PRV55912,3000,PHY425136,PHY419697,NaN,2009-08-16,4280,1068.0,2009-08-19,235,4280,25000,42731,V4581,41400,71690,4148,73300,2859,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33610,BENE134045,CLM47937,2009-04-21,2009-04-27,PRV55912,11000,PHY390614,PHY416976,NaN,2009-04-21,51881,1068.0,2009-04-27,197,51881,2930,03842,25000,5845,2768,5070,47875,4238,2762,9671.0,NaN,NaN,NaN,NaN,NaN
33672,BENE134279,CLM44594,2009-03-29,2009-04-05,PRV55912,10000,PHY431474,PHY330172,NaN,2009-03-29,99591,1068.0,2009-04-05,865,0389,41400,59010,27651,41071,486,34590,5119,99591,NaN,598.0,5849.0,NaN,NaN,NaN,NaN
35166,BENE140302,CLM54326,2009-06-05,2009-06-15,PRV55912,44000,PHY382830,PHY423769,NaN,2009-06-05,7907,1068.0,2009-06-15,245,4240,42731,7994,42832,4142,4280,2851,5990,2859,NaN,3521.0,5185.0,NaN,NaN,NaN,NaN
35306,BENE140781,CLM39863,2009-02-24,2009-03-02,PRV55912,11000,PHY429928,PHY412654,NaN,2009-02-24,4279,1068.0,2009-03-02,218,42731,4240,3804,4019,V1582,V0481,42789,V1042,29680,49390,3772.0,3320.0,NaN,NaN,NaN,NaN
38400,BENE151784,CLM51793,2009-05-19,2009-05-31,PRV55912,10000,PHY418191,PHY335210,PHY387346,2009-05-19,71535,1068.0,2009-05-31,494,82009,42731,2724,2851,58881,7843,28529,42831,E8889,4019,8151.0,4019.0,NaN,NaN,NaN,NaN
39594,BENE155971,CLM54337,2009-06-05,2009-06-11,PRV55912,4000,PHY399908,NaN,NaN,2009-06-05,4660,1068.0,2009-06-11,180,49121,29650,5859,2724,4169,V1011,E8499,59970,25002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39909,BENE157145,CLM49309,2009-05-01,2009-05-02,PRV55912,4000,PHY352158,NaN,NaN,2009-05-01,78659,1068.0,2009-05-02,904,9693,78009,E9504,78900,4111,30401,78079,E8490,V1041,V4365,NaN,NaN,NaN,NaN,NaN,NaN
39959,BENE157377,CLM33391,2009-01-11,2009-01-14,PRV55912,1000,PHY380413,NaN,NaN,2009-01-11,43811,1068.0,2009-01-14,040,33119,2449,5990,3320,2989,41400,4019,4280,7812,NaN,NaN,NaN,NaN,NaN,NaN,NaN